In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
NoOfPaths = 2
NoOfSteps = 5
Z = np.random.normal(0.0,1.0,[NoOfPaths,NoOfSteps])
X = np.zeros([NoOfPaths, NoOfSteps+1])
S = np.zeros([NoOfPaths, NoOfSteps+1])
time = np.zeros([NoOfSteps+1])

In [11]:
Z

array([[ 0.39789946,  2.17637945,  0.61471058, -0.18385282, -0.23027534],
       [ 0.10889478,  0.30886168,  1.39159114, -2.27810772, -0.10297621]])

In [15]:
X

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
time

array([0., 0., 0., 0., 0., 0.])

In [3]:
def GeneratePathsGBMABM(NoOfPaths,NoOfSteps,T,r,sigma,S_0):    
    
    # Fixing random seed
    np.random.seed(1)
        
    Z = np.random.normal(0.0,1.0,[NoOfPaths,NoOfSteps])
    X = np.zeros([NoOfPaths, NoOfSteps+1])
    S = np.zeros([NoOfPaths, NoOfSteps+1])
    time = np.zeros([NoOfSteps+1])
        
    X[:,0] = np.log(S_0)
    
    dt = T / float(NoOfSteps)
    for i in range(0,NoOfSteps):
        # making sure that samples from normal have mean 0 and variance 1
        if NoOfPaths > 1:
            Z[:,i] = (Z[:,i] - np.mean(Z[:,i])) / np.std(Z[:,i])
        #ABM    
        X[:,i+1] = X[:,i] + (r - 0.5 * sigma **2 ) * dt + sigma * np.power(dt, 0.5)*Z[:,i]
        time[i+1] = time[i] + dt
        
    #Compute exponent of ABM
    S = np.exp(X)
    paths = {"time":time,"X":X,"S":S}
    return paths


In [9]:
def mainCalculation():
    NoOfPaths = 50000
    NoOfSteps = 1000
    T = 1
    r = 0.05
    sigma = 0.4
    S_0 = 100
    
    M = lambda r,t : np.exp(r**t)
    
    Paths = GeneratePathsGBMABM(NoOfPaths,NoOfSteps,T,r,sigma,S_0)
    timeGrid = Paths["time"]
    X = Paths["X"]
    S = Paths["S"]
    
    #plt.figure(1)
    #plt.plot(timeGrid, np.transpose(X))   
    #plt.grid()
    #plt.xlabel("time")
    #plt.ylabel("X(t)")
    
    #plt.figure(2)
    #plt.plot(timeGrid, np.transpose(S))   
    #plt.grid()
    #plt.xlabel("time")
    #plt.ylabel("S(t)")
    
    # Checking martingale property
    # not discounted
    # checking expectation of future stock value not equal to S0 so not a martingale
    ES = np.mean(S[:,-1])
    print(ES)
    
    # discounted
    # improved close to S0 if we increase NoOfPaths
    ESM = np.mean(S[:,-1]/M(r,T))
    print(ESM)
    
    # We have convergence
    
mainCalculation()

105.0564187201596
99.93275671928345
